title: Imagine It Better Framework
email: absolutetabletop@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
        This repository is the open source project that is the Imagine it Better Game Design framework. 
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://imagineitbetter.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ImagineItBetter 
github_username:  ImagineItBetter
domain: imagineitbetter.github.io

permalink: pretty

# Build settings
theme: just-the-docs
# plugins:
  # - jekyll-feed
  # - jekyll-seo-tag
